### ISSUE TITLE
auto complete

### ISSUE THREAD

**Issue by helsmy** [amsitlab/termuxlauncher#12]
Tapping some long app name is unbearable. Is there any solution for autocomplete app name?

**Comment by amsitlab** [comment]
Iook nice, i will try to add on next version.
But if you using bash as your shell, you can write simple function to your ~/.bashrc or ~/.bash_profile
`launch_completion() {
	
	local curr perv apps
	COMPREPLY=()
	curr="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	apps=$(launch -l | tr '\n' ' ')
	COMPREPLY=( $(compgen -W "${apps}" -- ${curr}) ) 
}
complete -F launch_completion launch`

**Comment by amsitlab** [comment]
Look nice, I will try to iadd on next version
If you use bash as your shell, you can write simple function to your ~/.bashrc or ~/.bash_profile
```
launch_completion() {
	
	local curr perv apps
	COMPREPLY=()
	curr="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	apps=$(launch -l | tr '\n' ' ')
	COMPREPLY=( $(compgen -W "${apps}" -- ${curr}) ) 
}
complete -F launch_completion launch```

**Comment by amsitlab** [comment]
Will add on next version.
For now , if you using bash as shell, you can write simple function to ~/.bashrc or ~/.bash_profile
```launch_completion() {
	
	local curr perv apps
	COMPREPLY=()
	curr="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	apps=$(launch --list | tr '\n' ' ')
	COMPREPLY=( $(compgen -W "${apps}" -- ${curr}) ) 
}
complete -F launch_completion launch```

**Comment by amsitlab** [comment]
Will add on next version.
For now , if you using bash as shell, you can write simple function to ~/.bashrc or ~/.bash_profile
```
launch_completion() {
	
	local curr perv apps
	COMPREPLY=()
	curr="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	apps=$(launch -l | tr '\n' ' ')
	COMPREPLY=( $(compgen -W "${apps}" -- ${curr}) ) 
}
complete -F launch_completion launch```

**Comment by amsitlab** [comment]
Will add on next version.
For now , if you using bash as shell, you can write simple function to ~/.bashrc or ~/.bash_profile
```
launch_completion() {
	
	local curr perv apps
	COMPREPLY=()
	curr="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	apps=$(launch -l | tr '\n' ' ')
	COMPREPLY=( $(compgen -W "${apps}" -- ${curr}) ) 
}
complete -F launch_completion launch
```

**Comment by helsmy** [comment]
thanks for reply. I will try. :smile:

**Comment by pguimier** [comment]
This works like a charm, but typing 'laun<>TAB' suggest the launch_completion aswell. 
Some tipps :
- rename the function with maj or heading _
- add an alias for launch with one char command ( I use ':') 
   Eg: alias :='launch'
- add your shortcut in the autocompletion.
    Eg: complete -F _launch_completion launch :
