### ISSUE TITLE
Termux launcher stopped working

### ISSUE THREAD

**Issue by xoxxxoooxoxo** [amsitlab/termuxlauncher#2]
'classes.dex'...
Unable to add 'classes.dex' to 'termuxlauncher-unsigned.apk': file not found

Please tell me what to do now...
Please

**Comment by amsitlab** [comment]
please make sure , you has installing pacakages:
* ecj
* dx
* apksigner

try to remove dir
```bash rm -fr ./obj ./bin```
and rebubild
```bash ./build.sh```

**Comment by xoxxxoooxoxo** [comment]
Thanks for the reply sir,
but it is still not working. I don't know what is happening but it is
showing some kind of error in the proccess. can you please send me the
commands from first ? like in a order from first to last ? what packages
are required (btw i have all the packages you mentioned above.) , device
requres root or not or anything else ? i am actually new to this
environment and i am an young aspiring programmer. You are the only person
on the planet who said termux can launch apps and i am sooo impressed so
can you please help me with this ?
i appreciate it :)

**Comment by amsitlab** [comment]
No required root.
You can download [this](https://github.com/amsitlab/termuxlauncher/raw/master/bin/termuxlauncher.apk) Apk file and install on your device . give me result after you installing it.

**Comment by xoxxxoooxoxo** [comment]
i downloaded it but it is not installing

On Aug 7, 2018 16:04, "Amsit S" <notifications@github.com> wrote:

No required root.
You can download this
<https://github.com/amsitlab/termuxlauncher/raw/master/bin/termuxlauncher.apk>
Apk file and install on your device . give me result after you installing
it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/amsitlab/termuxlauncher/issues/2#issuecomment-411012563>,
or mute the thread

**Comment by amsitlab** [comment]
Try to download apk file on [releases](https://github.com/amsitlab/termuxlauncher/releases) page.
Before you install, make sure installing apk file from unknown source is enable.
1. Goto Settings
2. Goto Security
3. Unknown Source (enable)

**Comment by xoxxxoooxoxo** [comment]
I installed it and it started.
Now what ?
I mean how to launch any app ?
Like are there any commands to launch downloaded apps like instagram,
shareit or chrome ?
Please tell me

**Comment by amsitlab** [comment]
Please read README.md file on this repo look at Recommended section.

**Comment by amsitlab** [comment]
Read [here](https://github.com/amsitlab/termuxlauncher/blob/master/README.md#recomended)
