### ISSUE TITLE
build.sh apksigner Unsupported command

### ISSUE THREAD

**Issue by hkamuc** [amsitlab/termuxlauncher#20]
the call for apksigner is resulting in:

> apksigner begun: creating termuxlauncher.apk

> Unsupported command: ../termuxlauncher-debug.key. See --help for supported commands

**Comment by amsitlab** [comment]
5e77285

**Comment by SeifTechnon** [comment]
$ apksigner autokey
Unsupported command: autokey. See --help for supported commands?
