### ISSUE TITLE
Launch an executable rather than function

### ISSUE THREAD

**Issue by pulketo** [amsitlab/termuxlauncher#3]
Why not, convert launch to executable rather than to be a function
So i wont "source it" again and again whenever i install some app.

**Comment by amsitlab** [comment]
Cause termux launcher read installed app on device before launch app.

**Comment by amsitlab** [comment]
Btw, if you installing new app on your device, you just tap/resart termuxlaucher app , laucher script will be update automatic for you, and you can launch app on termux without "source" again.
> if app still not launch after you type `launch <appname>`
> try to exit current termux session or try with new session,  or you can also type `termux-reload-settings`
> to ensure ~/.bashrc contents has been updated.

**Comment by huayem** [comment]
I had fix the problem about permision denied.

Thank you for having me your excelence termuxlauncher.
