### ISSUE TITLE
Exit codes

### ISSUE THREAD

**Issue by pulketo** [amsitlab/termuxlauncher#5]
Could you please add exit codes 
exit 0 if everything is ok
Exit 1 if app not found or error

**Comment by amsitlab** [comment]
If app is not found or not installed on your device when you typing "launch" command, help message will be displayed .

**Comment by pulketo** [comment]
A help message won't work when you want to execute another command in case command is not found or another error.

**Comment by amsitlab** [comment]
I has fix it on 638ea6d10d9ec6a89b9ca5b406e3a4e8976fa534 , you can download new apk version from [releases](http://github.com/amsitlab/termuxlauncher/releases) page.

**Comment by amsitlab** [comment]
feel free to open new issue.

**Comment by huayem** [comment]
I had termux launcher issue. I used the revised apk from release.

bash: /sdcard/termuxlauncher/.apps-launcher: Permission denied

**Comment by bitsmanent** [comment]
> I had termux launcher issue. I used the revised apk from release.
> 
> bash: /sdcard/termuxlauncher/.apps-launcher: Permission denied

Make sure termux (not the launcher) has storage access permissions.
