### ISSUE TITLE
Youtube is not launching

### ISSUE THREAD

**Issue by pulketo** [amsitlab/termuxlauncher#6]
Hello, when I do:
launch YouTube, it just won't launch...
then to debug i did:
$ am start -n com.google.android.youtube/.app.honeycomb.Shell$HomeActivity --user 0
**Starting: Intent { cmp=com.google.android.youtube/.app.honeycomb.Shell }
Error type 3
Error: Activity class {com.google.android.youtube/com.google.android.youtube.app.honeycomb.Shell} does not exist.**
thanks

**Comment by pulketo** [comment]
Ok, it's because shell is interpreting $HomeActivity as a variable, if you 
quote it like this:
am start -n 'com.google.android.youtube/.app.honeycomb.Shell$HomeActivity'
it will run

**Comment by amsitlab** [comment]
Activity with nested class.
Thank for your report,  I'll update latter, if you see another bugs/error please tell me.

**Comment by amsitlab** [comment]
I has update it.

**Comment by Munishh992** [comment]
hi @pulketo , i am facing similar issue and i am using below code   options.Add("appium:appPackage", "com.google.android.youtube");
  options.Add("appium:appActivity", ".app.honeycomb.Shell$HomeActivity"); but i am facing issue . i checked in appium server log, there i am not getting quotes as you mentioned. kindly assist
