### ISSUE TITLE
In Fish shell..

### ISSUE THREAD

**Issue by MmxKnows** [amsitlab/termuxlauncher#8]
![img_20190112_181458](https://user-images.githubusercontent.com/45761847/51073378-0b2e4d00-1696-11e9-820e-be5c11257df8.jpg)

So.. 🤕

**Comment by amsitlab** [comment]
I'm sorry currently termux launcher only generate valid shell/bash script .. I will try to fix it in next release, for now you must be use bash/sh interpreter to run termuxlauncher, thank for issue.


Best regard.

**Comment by fdciabdul** [comment]
gabisa di install ya apps nya gan

**Comment by dm9pZCAq** [comment]
hello 
I found a way to use a **_launch_** on any shell

just execute this:

`echo -e "appl=\${EXTERNAL_STORAGE}/termuxlauncher/.apps-launcher;launch=\$PREFIX/bin/launch;if ! [ -f \"\$launch\" ]; then echo -e \"#\x21/bin/bash\nsource \$appl\nlaunch \\\$@\" > \$launch;chmod 755 \$launch;echo \"\n\e[1;32mdone\e[0m\";else echo \"\n\e[1mit seems there [\$launch] is already something\e[0m\";fi" | bash`

if your file [**_.apps-launcher_**] is located elsewhere, then change this path in command: 
_echo -e "appl=\\$**{EXTERNAL_STORAGE}/termuxlauncher/.apps-launcher** ; ..._

![image](https://user-images.githubusercontent.com/46228973/55643732-8e19fc00-57dc-11e9-86ae-a094629c48d2.png)


> ![img_20190112_181458](https://user-images.githubusercontent.com/45761847/51073378-0b2e4d00-1696-11e9-820e-be5c11257df8.jpg)
> 
> So.. 🤕

**Comment by MmxKnows** [comment]
Thanx man. Now It's working on fish shell 🤟
