### ISSUE TITLE
Hmm

### ISSUE THREAD

**Issue by fdciabdul** [amsitlab/termuxlauncher#9]
![screenshot_20190116_190705](https://user-images.githubusercontent.com/31664438/51248206-fddccf80-19c1-11e9-956a-6e1184f9a981.png)
Not compatible

**Comment by amsitlab** [comment]
@fdciabdul anjeun tiasa download [di die](https://github.com/amsitlab/termuxlauncher/releases/download/First/termuxlauncher.apk)

**Comment by amsitlab** [comment]
@fdciabdul bisa download nu [di dieu](https://github.com/amsitlab/termuxlauncher/releases/download/First/termuxlauncher.apk)

**Comment by fdciabdul** [comment]
oh jadi iyeuteh remodif nya

**Comment by fdciabdul** [comment]
atau kumaha kitu

**Comment by amsitlab** [comment]
Launcher.
Buka apps via command.

Contoh buka whatsapp:
`launch whatsapp`

Contoh buka youtube:
`launch youtube`

**Comment by fdciabdul** [comment]
nah masalahnateh appsna teubisa di install euy , hapa hp urang teu support kitu ?

**Comment by amsitlab** [comment]
Dowload apa compile?

**Comment by fdciabdul** [comment]
install na wa,  compile namah bisa,  nah pas di install na tidak terpasang wae nya

**Comment by amsitlab** [comment]
Download [iyeu](https://github.com/amsitlab/termuxlauncher/releases/download/First/termuxlauncher.apk) wee tinggal install, tong di compile.
